apiVersion: v1
kind: Service
metadata:
  name: estadisticas-service-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: estadisticas-service
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006